version: '3.9'

services:
  postgres:
    image: postgres:15.1-alpine3.16
    container_name: server_db
    env_file:
      - postgres.env
    ports:
      - "8001:5432"
    networks:
      iva_net:
        ipv4_address: 1.0.1.2
    restart: always

  iva_admin:
    build:
      context: .
      dockerfile: iva_admin.Dockerfile
    container_name: iva_admin
    env_file:
      - iva_admin.env
    volumes:
      - ./iva_admin:/app
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    networks:
      iva_net:
        ipv4_address: 1.0.1.3
    restart: always

  server_mon:
    build:
      context: .
      dockerfile: server_mon.Dockerfile
    container_name: server_mon
    env_file:
        - server_mon.env
    volumes:
      - ./server_mon:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      iva_net:
        ipv4_address: 1.0.1.1
    restart: always

networks:
  iva_net:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.1.0/28
          gateway: 1.0.1.14